### PR TITLE
 add linters,index html,style css

### PR DESCRIPTION
**Pull request by Hirwacardinalloic**
## Description
 In this PR, we installed linters, webhint of html, and stylelint of css 

### General requirements 
- [x] No linter errors.
- [x] Correct **Github flow**.
- [x] Professional Documentation. 

### Project requirements, We: 
- [x]  Added linters, index HTML, style CSS

 # Happy reviewing 😃

### CODE REVIEW

**Review by gtekle — CHANGES_REQUESTED** [review]
Hi @Hirwacardinalloic :wave:, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
dog-pug


## Highlights
:heavy_check_mark: Linters setup correctly
:heavy_check_mark: No linter errors
:heavy_check_mark: Good use Github flow
:heavy_check_mark: Good use of .gitignore

## Required Changes ♻️
_Check the comments under the review._

- [ ] You should add a professional Readme according to the [template](https://github.com/microverseinc/readme-template/blob/master/README.md) provided by Microverse for it helps your repo look more professional and aid new comers navigate your project easily. 
image

- [ ] Pull request summary should reflect the changes that are made in the pull request. I like the way your organized your summary in to subtopics. However, there was not unit test done in this pull request. Thus, kindly correct the summary to align with the changes made.
image

## Optional suggestions

- [ OPTIONAL ] I believe the pull request title could be improved to reflect changes made. For example, `Hello Microverse: Project Setup` could be a good candidate and we can derive this from the topic of the activity.
image
#### CURRENT PR TITLE
image

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Hirwacardinalloic** [comment]
thanks for your Advice, let me make a good one

**Review by phelian23 — APPROVED** [review]
Hi @Hirwacardinalloic, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by topeogunleye — APPROVED** [review]
### **STATUS: APPROVED  ✔️** 
------
Hi @Hirwacardinalloic,  

Your project is complete! Great job for nailing it right on the first attempt 🥇. There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟
congratulations

## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Followed Github flow :heavy_check_mark:
- Professional README file. :heavy_check_mark:
- PR has a good title and description :heavy_check_mark:

> ## [Optional] suggestions:
> * [ ]  Please check my inline comments.
> 
> _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
> 
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
